aws/aws-graviton-getting-started

README.md

*Description of changes:* Improve Debugging Problems section

Improve Debugging Problems section

---

README.md

bug #1 
add comment about ffmpeg release version that will contain ARM64 performance changes.

fix bug #1: add comment about ffmpeg release version

---

CommonNativeJarsTable.md

Update CommonNativeJarsTable.md to reflect new release of netty-epoll with Arm binary support.

Update CommonNativeJarsTable.md to reflect new netty-epoll release

---

README.md
sample-code/crc.c

Add crc example code

---

README.md
python.md

Tested on m6g and c5 instances.

instructions to install SciPy and NumPy with BLIS

---

README.md

Add known issue/workaround for Cassandra

---

README.md
c-c++.md
containers.md
java.md
optimizing.md
python.md

Split the various sections out into separate files, added a first pass of information/links on container-based workloads.
Feedback welcome! Thanks!

Add container workload information; Split sections out into separate files

---

README.md
golang.md

Added notes about Golang on Graviton.

added notes about go 1.16

---

README.md

Update to add M6gd, C6gd and R6gd instances

---

golang.md

*Description of changes:* Spelling fixes
@prekageo Thanks for noticing the my spelling mistake.

spelling fixes to golang.md

---

README.md

Add Ruby improvements

---

README.md

*Issue #, if available:* 
none
Added Cisco OpenH264 and alphabetized the recent software updates list.

added recent software update note about Cisco OpenH264 binary

---

README.md
amis.md
os.md

Add list of supported operating systems with links to AMIs

Add list of supported operating systems

---

README.md

Fix a typo in Cassandra section

Fix typo in Cassandra section

---

containers-workarounds.md
containers.md

Update containers.md and containers-workarounds.md to reflect merging of CSI driver support late last week.

Update EFS & EBS CSI Drivers

---

amis_cf_sm.md

Update and rename amis.md to amis_cf_sm.md

---

README.md

Add link to new T4g instance types and add paragraph about free trial until 12/31/2020

T4g README update

---

python.md

https://github.com/aws/aws-graviton-getting-started/issues/48
Update python.md with instructions for building Morfeusz from source, as detailed in [issue 48](https://github.com/aws/aws-graviton-getting-started/issues/48)
Once merged, we can close the issue.

Update python.md with Morfeusz instructions

---

CommonNativeJarsTable.md

Update CommonNativeJarsTable.md to add arm build status of Sigar and Hadoop-lzo package

Add build status of Sigar and Hadoop-lzo package

---

CommonNativeJarsTable.md

Commons crypto was released for Arm64

---

README.md

Describe zlib, its many forks and the work done to improve decompression performance in zlib-cloudflare for ARM and x86 platforms.

Add documentation for zlib

---

c-c++.md

Mention signed vs. unsigned char

---

java.md

Add some useful java jvm options

---

python.md

Updating PyTorch wheel availability

---

dpdk_spdk.md

DPDK 20.11 onward has Gv2 native optimization

---

README.md
tensorflow.md

Instructions on how to build TensorFlow on Graviton2 with Ubuntu 20.04.

add instructions on how to build tensorflow for arm64

---

containers-workarounds.md
containers.md

Update supported software; Add Terraform and Pulumi to tracker

Update supported software; Add Terraform and Pulumi to tracker

---

dpdk_spdk.md

Add DPDK known issues

---

README.md

1. Bazil link to latest
2. Ruby 3.0 released with improved arm64 support
3. HAProxy 2.4

updated supported software packages

---

README.md

Update  Recent software updates relevant to Graviton

---

README.md

Provide instructions to get the src, build and install. Also, add info for AWS service users about zlib option.

Update zlib entry; add instructions to get and use zlib-cloudflare

---

java.md

Suggest Corretto for outline-atomics changes

---

README.md

Fix spelling of performance in the table reference to Ruby version that should be used.

Fix minor typo in readme.md

---

containers.md

Here are a few proposed additions regarding how to actually run a mix of x86 and Graviton instance types in a k8s cluster and sort out taints, scheduling, auto-scaling, etc.

Add additional notes regarding running Graviton instances with Kubernetes

---

java.md

Fixed a typo on the Java page.

Fixed a typo on the Java sample

---

README.md
rust.md

Start a Rust language page

---

README.md

Document mongodb versions with improved Graviton2 support.

recent software update: add mongodb

---

java.md

learnings from @honeycombio. our loss, your gain!
documents that apache kafka benefits significantly from moutline-atomics

Add explicit note about apache kafka

---

README.md

Add 2M RPS HAProxy results

---

c-c++.md

Update LSE language to say it's default with GCC-10 and AL2

---

README.md

Add a section about postgres

---

README.md

Add documentation recommending MySQL 8.0.23+

README: add MySQL 8.0.23+ suggestion

---

python.md

added information about Python 3.6 on Centos and RHEL 8

WORK IN PROGRESS: added information about Python 3.6 on Centos and RHEL 8

---

containers-workarounds.md
containers.md

Update external-dns k8s support; Initial tracking of ArgoCD 

Update external-dns k8s support; Track argoCD issue

---

containers-workarounds.md
containers.md

- Move Pulumi to supported (it is since v2.23)
- Add ArgoCD and Flatcar to workaround page

Update container support

---

README.md

To follow changing URLs of documents provided by ARM.

Update URLs of ARM documents

---

containers.md

docs: fix typo

---

os.md

Add FreeBSD 13.0 and update FreeBSD 12.1

---

README.md
SIMD_and_vectorization.md

Port patches to main (from master.)
Add link to the SIMD page from the main page.
Add links to Arm NEON documentation and intrinsics search engine.

SIMD_and_vectorization.md

---

containers-workarounds.md

added Istio build instructions

---

containers.md

Add link to Istio container build instructions

---

os.md

Additional entries for community Linux distributions - not all have AMI's available yet or Marketplace listings so we'll need to circle back and update as those become available.

Add Alpine , Alma Linux, Debian 11, and Rocky Linux

---

os.md

Removing note about needing to confirm support.

Debian 11 LSE support confirmed

---

perfrunbook/utilities/configure_graviton_metal_iommu.sh
perfrunbook/utilities/configure_mem_size.sh

Update the perf-runbook tools with fixes for nits and some bugs on Ubuntu 20.04 updating grub.

perfrunbook: Update tools with style fixes and minor bug fixes

---

perfrunbook/utilities/configure_vcpus.sh
perfrunbook/utilities/install_perfrunbook_dependencies.sh

Fix typos in scripts, and improve dependency install script to recognize all minor versions of Ubuntu 20.04 LTS.

perfrunbook: Fix typos in scripts, and improve dependency install script

---

os.md

Adding link for Debian 11 marketplace images.

Adding link for Debian 11 marketplace images

---

os.md

Fix typo in RHEL

---

README.md

Remove T4g trial details as the trial has ended

---

os.md

Signed-off-by: Elkhan Mammadli <elkhan.mammadli@protonmail.com>
Update AlmaLinux Informations and AMI link

Update AlmaLinux Informations and AMI link

---

python.md

[python.md] Add the min. recommended versions for openBLAS/scipy/numpy

---

containers.md
tensorflow.md

update the tensorflow container link to point to the latest

---

c-c++.md

LSE is supported on all Graviton2 and Graviton3 instances

---

containers-workarounds.md
containers.md

Refresh container image and OS support.

Update container image and OS support

---

containers.md

Typo correction

---

golang.md

*Description of changes:* Document performance improvements for Go 1.17 and 1.18

Add performance notes for recent Go versions

---

os.md

Update kernel versions for AL2 that contain recent enhancements for Graviton2.

Update minimum recommended Linux kernel versions for Amazon Linux 2.

---

README.md

Add Graviton3/c7g information

---

c-c++.md

Update compilers for Graviton3

---

perfrunbook/debug_code_perf.md

Add section to performance runbook on how to collect profiles using pseudo-nmi to see inside non-preemptible sections of the Linux kernel.

Add steps for how to use pseudo-nmi for collecting on-cpu profiles

---

dotnet.md

Add additional .NET 6 on Graviton resources for reference.

Update .NET 6 details based on release

---

machinelearning/tensorflow.md

Updated the mlcommons and gcc versions, and also added details on some of the
additional wheels to be installed, and removed the PRs that got merged recently.
*Issue #, if available:* Not applicable
*Description of changes:* updates to the tensorflow userguide 

update the tensorflow userguide for mlcommons and gcc versions

---

README.md
python.md

fix the broken links for ML packages

---

README.md

Added additional guidance for the latest improvements available in the latest
versions of ffmpeg.

readme.md - update ffmpeg guidance

---

README.md

Fix Rng instruction in table

---

README.md

Resolves: https://github.com/aws/aws-graviton-getting-started/issues/246

README.md: Update title and description

---

java.md

document AES/GCM performance improvement and flags

[java] document AES/GCM performance improvement and flags

---

machinelearning/pytorch.md

[machinelearning] add pytorch user guide

---

transition-guide.md

Added advice on adjusting threshold levels on EC2 ASG if these are utilized. Otherwise price/performance is not optimized if EC2 scales out based on lower threshold values.

Added advice on adjusting thresholds on EC2 ASG

---

DataAnalytics.md
README.md

Adding some general guidelines/recommendations that will be helpful for users trying to improve application performance across Spark clusters. 

Add general guidelines for Spark on Graviton

---

README.md

change "here" links to be more descriptive and remove Graviton version where irrelevant.

add m7g to README.md

---

python.md
software/librdkafka.md

Add information on librdkafka and confluent_kafka Python module

Add information on librdkafka and confluent_kafka Python module

---

README.md
machinelearning/pytorch.md

This PR updates the pytorch user guide with the upcoming 2.0 release improvements, adds torch bench benchmark details, and cleans up the outdated code snippets.

[machine learning] update pytorch user guide with pytorch 2.0 improvements

---

amis_cf_sm.md

Add information on finding Amazon Linux 2023 AMIs

Add information on finding Amazon Linux 2023 AMIs

---

python.md

Updating the documentation to clarify that Python 3.6 has reached its EOL phase.

Update python.md documentation

---

c-c++.md

Add Amazon Linux 2023 to C/C++ Recommendations

---

os.md

Add AL2023 to Linux distro table

---

java.md

Update java.md to add Kotlin, Scala, and Groovy reference.

---

aws-lambda/README.md

Fix markdown links in AWS Lambda README.md

Fix links in AWS Lambda README.md

---

perfrunbook/utilities/measure_aggregated_pmu_stats.py

Update the measure_aggregated_pmu_stats.py tool to account for PMU events differences between Graviton2 and 3 for the mesh interconnect, as before we were collecting the wrong events for virtual memory maintenance operations on Graviton3.

Update Arm CMN mesh PMU events for Graviton2/3

---

python.md

added guidance on python wheel open3d

added guidance on python wheel open3d

---

os.md

updating the table to include Flatcar

adding Flatcar

---

perfrunbook/debug_hw_perf.md

Clarify and disambiguate terminology usage around the PMU in regards to events and counters and editted
text that uses these terms interchangeably to be more consistent in perfrunbook/debug_hw_perf.md

Clarify and disambiguate terminology usage around the PMU in debug_hw_perf.md

---

HPC/README.md
HPC/scripts-wrf/scripts-wps/0-install_jasper.sh
HPC/scripts-wrf/scripts-wps/compile-wps.sh

Add scripts to install WRF Pre-Processing System (WPS). Credit and thanks to juntangc@. 

Add scripts to install WRF Pre-Processing System (WPS)

---

perfrunbook/debug_code_perf.md

Typo (libperf-jvmti.so) in debug_code_perf.md

Typo in debug_code_perf.md

---

perfrunbook/utilities/measure_aggregated_pmu_stats.py
perfrunbook/utilities/measure_and_plot_basic_pmu_counters.py

Update measure_and_plot_basic_pmu_counters.py to collect basic events for 6a, 7a, and 7i EC2 instance families.  Fix a bug in the script that would label any custom event ratio as `ipc` by extending how to define a custom ratio as --custom_ctr "<stat_name>|<ctr1>|<ctr2>|scale"
Update measure_aggregated_pmu_stats.py to collect and aggregate PMU event ratios for 6a, 7a and 7i EC2 instance families.

perfrunbook/utilities: Update PMU event collection scripts

---

perfrunbook/optimization_recommendation.md

Update optimization_recommendation.md with recommendation to disable autocorking

disable autocorking

---

README.md
arm64-assembly-optimization.md

This is the first post of the assembly guide, which I plan to add a section to about once every two weeks until I run out of sections. (8-10 sections are likely)

Assembly guide, post 1

---

machinelearning/pytorch.md

update pytorch user guide with pytorch 2.1 details

[machine learning] update pytorch user guide with pytorch 2.1 details

---

README.md
php-opcache-al2.md
php.md

Add build and install instructions for PHP OPcache on AL2.

Add PHP OPcache for AL2

---

aws-lambda/GravitonLambdaNumber/test/event.json

This context was pre-filled and contained hardcoded values for account ID, IP addresses, and other fields which should be auto-filled or are not relevant.

Lambda: Remove static request context and headers

---

dotnet.md

Added a row for the newly released .Net 8.

Update dotnet.md for .Net 8 release

---

HPC/README.md

add OpenRadioss (Altair) to the HPC application list available on Graviton

add OpenRadioss (Altair) to the list

---

arm64-assembly-optimization.md

assembly guide: added "Split Data Dependency Chains"

---

os.md

Added content about Windows as we get questions about this. The OS page should list what's supported and what's not.

Update os.md mention no support for windows

---

c-c++.md

updated c/c++ flag guidance again

---

perfrunbook/debug_hw_perf.md

Add quick-start instructions for how to access the Statistical Profiling Extension PMU for Graviton metal platforms to the perfrunbook.  Covers how to check for it on Amazon Linux and Ubuntu distros.

perfrunbook: Add basic instructions for accessing SPE

---

aws-lambda/GravitonLambdaNumber/src/Dockerfile
aws-lambda/GravitonLambdaNumber/src/package.json
aws-lambda/GravitonLambdaNumber/template.yml
aws-lambda/README.md

update versions of various dependencies

update aws-lambda example

---

arm64-assembly-optimization.md

Assembly guide 03

---

machinelearning/pytorch.md

adding PyTorch Java details to user guide

pytorch user guide: add PyTorch Java details

---

machinelearning/onnx.md

machine learning: Add ONNX user guide

---

managed_services.md

Remove explicit Graviton2 references on intro section of this page.

---

machinelearning/onnx.md

machine learning: onnx: fix the benchmarking steps

---

HPC/README.md

Added EDF R&D Code Saturne
Added Code Saturne to the list

Update README.md 

---

HPC/README.md
HPC/scripts-code_saturne/cs_user_parameters.c
HPC/scripts-code_saturne/install-codesaturne-gcc-mpi4.sh
HPC/scripts-code_saturne/submit-F128-2-hpc7g-gcc-mpi4.sh

Add the build and run instructions for Code Saturne on Hpc7g.

add build/run instructions for code saturne

---

arm64-assembly-optimization.md

assembly guide: add new section: specialize

---

README.md

add Graviton blogs to README

---

README.md

Added new Molecular Dynamics blog link

---

README.md

add onnx blog to the list of ML blog posts

---

machinelearning/tensorflow.md

tensorflow: fix DLC pull instructions

---

arm64-assembly-optimization.md

assembly guide: added other resources

---

README.md

add LLM blog to the list of Machine Learning Blog posts

---

README.md

add newer blogs and case studies

---

machinelearning/tensorflow.md

TensorFlow deep learning container, wheel, and docker image details are updated. xla section is removed because the latest release integrated openXLA which requires changes in the build and usage. will update the userguide with XLA details once openXLA is validated on Graviton.

tensorflow: update the userguide with the latest release details

---

README.md
nodejs.md

added nodejs documentation

---

README.md
os.md

Update README.md with Gv4 specific information.  Update os.md with latest FreeBSD information for Graviton.

Update front-page to contain Graviton4 information

---

README.md

Graviton4 is a Arm v9 processor and that is implictly paired with v8.5

---

containers.md

*Issue #, if available:* No
*Description of changes:*  Added Kublr to this list

Added Kublr to containers.md

---

perfrunbook/optimization_recommendation.md

Add folios to optimization recommendations if running on Linux kernel >=6.9.

perfrunbook: Add description of folios

---

arm64-assembly-optimization.md

aog: add Use Efficient Instructions

---

README.md

Add https://pytorch.org/blog/accelerated-pytorch-inference/ to the Machine Learning blog list.

Add Pytorch blog for torch.compile

---

README.md
machinelearning/llama.cpp.md

machine learning: add llama.cpp user guide

---

arm64-assembly-optimization.md

aog: add an example to "Use Efficient Instructions"

---

golang.md

New guidance regarding `GOMAXPROCS` in a container.

updated golang guidance

---

README.md

adding ML and HPC blog post and case study links

---

java.md

Adding Java Graviton Migration Checklist to the Java on Graviton section of the AWS Graviton Technical Guide

Java Graviton Migration Checklist

---

os.md

Adding information about Debian 12 to the OS support page.

Added Debian 12 to the OS page

---

c-c++.md

I really enjoyed using this project, nice work! Found a couple of typos in the c-c++.md though 😛
version -> version

Update c-c++.md, fix a typo

---

java.md

Add hints to java.md about removing anti-patterns from Java code, such as hot exception code-paths.  Also update the best ways to profile Java code to recommend APerf as the first choice.

Update java.md with new recommendations about optimizations and profiling.

---

README.md

Added suggestion to use Cassandra 5 on JDK 17 to improve performance and scalability

Cassandra5 suggestion

---

machinelearning/llama.cpp.md

[machinelearning] update llama.cpp user guide

---

c-c++.md

Remove outline-atomics paragraph since not relevant anymore

remove outline-atomics paragraph

---

README.md
machinelearning/llama.cpp.md

add a section on how to run deepseek R1 on Graviton

---

dotnet.md

*Description of changes:* Update the .Net support table to show .Net 9 release date and arm64 improvement

Update .Net 9 release

---

README.md

Add a new blog in ML on Graviton

Add a new blog in ML on Graviton

---

README.md

This PR specifies what ARM Execution states Graviton CPUs support. It is based on https://developer.arm.com/documentation/ka006014/latest/ .

32/64 bit ARM Execution State support in Graviton CPUs

---

README.md

add APerf blog link to the blogs section

add APerf blog link to the blogs section

---

python.md

Update Python EOL information
