README.md
James Greenhalgh from ARM pointed out that we were missing +crypto to the march flag.
=> add missing +crypto to march flags for Graviton2

CommonNativeJarsTable.md
Update the CommonNativeJarsTable.md with new information as of 16-06-2020.
=> Update Jars table with version numbers for artifacts

README.md
Should we have a section on "Recommendations" or "Performance Recommendations"? This feels even more shoved in than it was.
=> Add AL2 recommendation for Cassandra

c-c++.md
Also add test to check whether libc uses LSE atomics or ld/st exclusives.
=> add AL2 to the list of systems that compile libc with LSE

README.md
Versions of pip <19.3 will fail to install wheel binaries built for Graviton2 using manylinux2014_aarch64, this describes the version needed to work around this and how to upgrade pip on the distribution being used.
=> Update known issues and workarounds for pip versions <19.3

containers-workarounds.md, containers.md
Add table in containers.md for explicit ecosystem support
Add containers-workarounds.md with details on workarounds
=> Add tables for ecosystem support and workarounds

README.md
Update bazelisk to latest release, confirmed it pulls the latest 3.6.0-linux-arm64 version on Graviton2
```
[ssm-user ~]$ sudo mv bazelisk-linux-arm64 /usr/local/bin/bazel
[ssm-user ~]$ bazel
2020/10/08 17:25:16 Downloading https://releases.bazel.build/3.6.0/release/bazel-3.6.0-linux-arm64...
Extracting Bazel installation...
[bazel release 3.6.0]
Usage: bazel <command> <options> ...
Available commands:
analyze-profile     Analyzes build profile data.
aquery              Analyzes the given targets and queries the action graph.
build               Builds the specified targets.
canonicalize-flags  Canonicalizes a list of bazel options.
clean               Removes output files and optionally stops the server.
coverage            Generates …
```
=> Update bazelisk to latest version

containers-workarounds.md, containers.md
ecs-cli now publishes arm64 binaries as of v1.20.0
=> Move ecs-cli to supported list

os.md
Link to AL2 AMIs was broken after the file was renamed from amis.md to amis_cf_sm.md
=> Fix broken link for AL2 AMIs

os.md
Note that Debian 10.7 includes backported kernel support for the Graviton2
bare-metal instance types.
Note that LSE support is scheduled for inclusion in Debian 11.
=> Update Debian bare-metal and LSE support details

c-c++.md, os.md
Ubuntu 18.04 does not come with libc6-lse installed by default.
An extra step is needed: `apt install libc6-lse`.
=> add Ubuntu 18.04 to list of systems with libc + LSE

c-c++.md
=> bug 72: add note that gcc-7 does not support rcpc and dotprod instrs

README.md
Cassandra installation works without requiring a workaround.
Verified on ubuntu 18.04.
removed workaround description
=> known issues: remove cassandra workaround

golang.md
Fix references to Go 1.16 as an upcoming release now it has been released (as of 2021/02/16)
=> Update now Go 1.16 has been released

README.md
Description of changes: Add newly launched X2gd instance to the readme page with a link to the instance webpage.
=> Add X2gd to the readme page

README.md
Updates the expected build flag
https://github.com/haproxy/haproxy/blob/3e6690a55513f2c10dfc7875b9ec2bb5333dee5f/INSTALL#L289
=> Updated HAProxy build flag in README.md

containers.md
Envoy now officially support arm64 since 1.16
=> Modified Envoy support to arm64

README.md
With Linux distribution parity between x86 and Arm64 the SandPiper tool has served its purpose and is now deprecated. This edit removes the link and replaces it with an existing package search tool at pkgs.org.
=> Remove link to SandPiper and replace with pkgs.org

SIMD_and_vectorization.md
Relevant procedure to port intrinsics code to NEON is a copy-paste from the c-c++ page: https://github.com/aws/aws-graviton-getting-started/blob/main/c-c%2B%2B.md#porting-codes-with-sseavx-intrinsics-to-neon
=> copy sse2neon section from c-c++ to SIMD file

java.md
When trying to find native libraries in a .jar file, if no .so file is found and an empty output is sent to "xargs file", it
triggers an error.
Using find .... -exec prevent the error from happening even when no file is found.
=> Prevent error when no .so file is found

python.md
Added recommandations to avoid EOL or soon to be EOL python versions
when adopting Graviton2.
Added a section about Anaconda support for Graviton2 with an example on
how to install numpy and pandas with Miniconda.
=> python version recommandations and Anaconda support

README.md
OpenJDK users need to follow different instructions to use zlib-cloudflare.
=> Update zlib instructions

containers.md
Calico and Cilium Multi arch images are available in docker hub and quay.io. Updating container.md to include Calico/Cilium 
=> Add Calico/ Update Cilium ARM support 

README.md
Closes #145
Updated relevant software section to note updated mongo builds with LSE support
=> Updated mongodb graviton support

tensorflow.md
Instructions on the existing tensorflow page end up in errors about missing AES instructions.
Tested new instructions on Ubuntu 20.04.
=> [tensorflow] update build instructions

perfrunbook/utilities/configure_vcpus.sh
online CPUs are not being visible to the docker run, hence even if the container is relaunched, it is still not able to utilize the cpus online'd after reboot.
This PR updates the docker cgroup cpuset.cpus to that of the host.  Both running and new container launches have been verified.
=> [utilities] update docker cgroup to reflect the correct vcpus

perfrunbook/utilities/measure_and_plot_basic_sysstat_stats.py
Patch that explicitly overrides any locales installed on AL2 or Ubuntu
when taking sysstat measurements to the ISO format.
=> perfrunbook: Explicitly specify timestamp format for sysstat/mpstat

transition-guide.md
When this page was created the performance runbook was part of main but has since moved to its on perfrunbook directory which broke the link here. Fixing it up.
=> Fix broken link to Performance Runbook

containers.md
Jaeger is already set with the multi-arch build since this [pull request](https://github.com/jaegertracing/jaeger/pull/3124).
=> doc: update jaeger status in containers doc

containers.md, tensorflow.md
This patch updates the tensorflow section with the latest status
and instructions to get TF based ML inference working on Graviton CPUs.
Also updated the supported containers list with the latest TF containers.
=> [ML inference]: Add tensorflow DLAMI and container details

perfrunbook/utilities/capture_flamegraphs.sh
Add tunable event capture frequency for oncpu and other perf-counter
events with the -f|--frequency flag. Add a tunable regex to filter perf-script output
with the -r|--regexfilter flag, the default behavior is to filter thread
names and combine stack traces from the same base name, i.e. GC-Thread-N
will show up as GC-Thread- instead of multiple traces for each
individual.  Add ability to define a custom perf event to capture on
instead of just oncpu|offcpu, can now specify any event that can be
passed to the -e flag in perf.
Ex: To capture traces of what code queues IO to block devices: `sudo ./capture_flamegraphs.sh block:block_bio_queue 60`
=> perfrunbook/utilities: Improve capture_flamegraphs.sh script

containers.md
Docker published a blog about speeding up docker buildx using EC2 Graviton instead of emulation. Add a link to that informative blog post.
=> Add link to Docker blog for native buildx

SIMD_and_vectorization.md
SIMDeverywhere provides a more complete automatic translation for x86_64 intrinsics.
=> Replace recommendation of sse2neon with SIMDe

containers.md
*Issue #, if available:* NA
*Description of changes:* Been testing PyTorch with ACL. Should we include a reference to the container image on this list?
=> Add link to PyTorch aarch64 container image

transition-guide.md
Add C7g instance type, update with re:Invent 2021 presentations and change all Graviton2 references to Graviton referring generically to the Graviton family of processors throughout this guide.
=> Transition guide updates since Graviton3 GA

perfrunbook/utilities/measure_and_plot_basic_pmu_counters.py
running the perfbook tool used to fail like this:
```
$ ~/aws-graviton-getting-started/perfrunbook/utilities/measure_and_plot_basic_pmu_counters.py --stat stall_backend_pkc --plot terminal --time 1
[...]
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```
That was due to the first line in the csv file being truncated.
The patch fixes this issue.
=> [perfrunbook/utilities] fix parse error

Monitoring_Tools_on_Graviton.md, README.md
This change request highlights some differences in utilities and tools available for monitoring on AWS Graviton processors compared to x86 processor architectures.
=> Graviton monitoring differences

containers.md
Per https://github.com/istio/istio/issues/26652:
arm64 support has official landed! Currently support is on the master branch. To try it out, follow: https://github.com/istio/istio/wiki/Dev-Builds#dev-release-information. Usage is the same - just istioctl install and you should be good to go.
Support will be included in the 1.15 release coming out in ~1 month.
=> Update Istio official Arm64 support status

CommonNativeJarsTable.md, java.md, python.md
5.10, update supported native jars, and update python
work-arounds for installing pip packages in the python.md section.
=> Update Java section about libperf-jvmti.so support from perf in Linux

containers.md
As of v1.15.0-beta the multi-arch Istio images are starting to show up in the Docker Hub repo here: https://hub.docker.com/r/istio/proxyv2/tags - adding this deatil to the getting started guide.
=> Add details / link to Istio multi-arch images

perfrunbook/debug_hw_perf.md, perfrunbook/utilities/capture_flamegraphs.sh, perfrunbook/utilities/install_perfrunbook_dependencies.sh, perfrunbook/utilities/measure_aggregated_pmu_stats.py, perfrunbook/utilities/measure_and_plot_basic_pmu_counters.py, perfrunbook/utilities/measure_and_plot_basic_sysstat_stats.py
Update measure_and_plot_basic_pmu/sysstat to eliminate matplotlib path as that is rarely used in favor of terminal plotting.
Update measure_and_plot_basic_pmu_counters.py to auto-detect CPU being run on and provide a dynamic set of ratios to profile as well as better align x86 and Graviton counters.
Add measure_aggregated_pmu_stats.py to collect a full range of counters at once to provide a summary of hardware performance instead of the more detailed time-series offered by the plot_basic_pmu_counters script.  Best for initial analysis of where a bottleneck may lie.
=> perfrunbook: Update utilities

java.md
Compilation policy and CodeCache heuristics have changed since Java 12.
This PR updates the CodeCache recommendation for Java versions 17 and later.
=> Update CodeCache recommendation for Java 17

transition-guide.md
Update Step 2 to include additional bullet referencing the newly released Porting Advisor for Graviton to help scan source trees.
=> Add reference to Porting Advisor for Graviton

SIMD_and_vectorization.md
With recent `clang` and `gcc`, only `__ARM_NEON` gets defined - but not `__ARM_NEON__`:
```
$ clang --version
clang version 17.0.0 (https://github.com/llvm/llvm-project.git b688b58f83ceb48dbe185be95372e45de1d51401)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ clang -dM -E -x c -mcpu=neoverse-n1 /dev/null | grep ARM_NEON
#define __ARM_NEON 1
#define __ARM_NEON_FP 0xE
$ gcc10-gcc --version
gcc10-gcc (GCC) 10.4.1 20221124 (Red Hat 10.4.0-1)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ gcc10-gcc -dM -E -x c -mcpu=neoverse-n1 /dev/null | grep ARM_NEON
#define __ARM_NEON 1
```
The correct check is …
=> Check for __ARM_NEON instead of __ARM_NEON__

java.md
suggest ACCP instead of +UseAESCTRIntrinsics -- it's more flexible, and easier to install regardless of whether you're using Corretto JVM / doesn't require tuning JVM flags.
=> suggest ACCP instead of +UseAESCTRIntrinsics

perfrunbook/utilities/install_perfrunbook_dependencies.sh
adding Amazon Linux 2023 if clause to install_perfrunbook_dependencies.sh and removing install for dstat and amazon-linux-extras
=> Amazon Linux 2023 added to install_perfrunbook_dependencies

README.md
Fix broken URL link reported by:
https://github.com/aws/aws-graviton-getting-started/issues/282
Update URL to the corrected link (not the PDF version)
=> fix broken link for "Neoverse N1 Software Optimization Guide"

README.md
Update the table with versions that customers have asked for guidance on, and packages known to have improved performance on Graviton: Cassandra, MariaDB, Postgresql, Spark
=> Update "Recent software updates" table

README.md
Fix a typo in the hardware description table for Graviton3
=> Fix typo: Graviton3 mesh is CMN-650, not CMN-700.

os.md
List of supported Ubuntu versions was out of date, and out of sync with other portions of the guide (which mention 22.04). 
=> Updated list of Ubuntu versions that support Graviton instances.

perfrunbook/debug_hw_perf.md
=> Clarify that sub-socket Graviton instance types don't provide access to all events

python.md
- Code to install Python does not work as is because of a duplicated `chmod +x` command
- Also fixes a few typos, feel free to correct me if I am wrong
=> Fix code typo on Python getting started

dotnet.md
I added .NET 7 to the .NET versions table, added notes for versions that are now out of support, and provided a link to an AWS re:Invent video for additional info for .NET 7 on Graviton (similar to the existing link for .NET 6).
My alias is kirkdavi@
=> Updated the .NET versions table

perfrunbook/utilities/capture_flamegraphs.sh
Update capture_flamegraphs.sh to take a -R or --reverse flag to produce stack reversed flamegraphs.  Stack reversed flamegraphs aggregate by leaf-function on the bottom taking the highest fraction of time, and the flames are all the stack paths taken to get to those leaf functions. This is useful when looking for optimization opportunities at the function level.
=> perfrunbook/utilities: Enable stack-reversed flamegraph to be produced

perfrunbook/optimization_recommendation.md
Add in JVM command line option recommendations to reduce TLB misses when the profiled code shows high instruction and/or data side TLB misses.
=> perfrunbook: Add optimization suggestions for TLB misses

HPC/README.md
Add a list of commercial software vendors and applications which support Graviton instances.
=> HPC: Add a list of HPC software

c-c++.md
Added a comment about the right way to use getchar() and check for EOF when coding in C - this is a *really* common bug, cause by developers using `char c` to get a character from `getchar` and then compare it with `EOF` (which is usually -1, but much like the signedness of `char`, is implementation defined).
=> Add some C standard advice

machinelearning/tensorflow.md
https://github.com/aws/aws-graviton-getting-started/issues/351
adding TensorFlow Java build instructions
=> tensorflow user guide: add TensorFlow Java build instructions

dotnet.md
*My alias*:  kirkdavi@
I added a link to the AWS Blog "**[Powering .NET 8 with AWS Graviton3: Benchmarks](https://aws.amazon.com/blogs/dotnet/powering-net-8-with-aws-graviton3-benchmarks/)**"
=> Added AWS blog link for .NET 8 on Graviton 3 to dotnet.md

perfrunbook/optimization_recommendation.md
Removed tcp_autocorking recommendation since fixed inside the kernel (latest and stable) and deployed on Amazon Linux and Ubuntu versions
=> Removed tcp_autocorking

perfrunbook/utilities/capture_flamegraphs.sh, perfrunbook/utilities/measure_and_plot_basic_pmu_counters.py
- fix issue where the 'no-root' logic was trying to read 'args' before it existed
This is a simple bug that got introduced a while back.
```
Traceback (most recent call last):
File "./aws-graviton-getting-started/perfrunbook/utilities/measure_and_plot_basic_pmu_counters.py", line 200, in <module>
if not args.no_root:
NameError: name 'args' is not defined
```
- don't get hung up if IMDS isn't available (e.g. in a container)
- don't depend on this script being run from the 'utilities' directory
Previously, the script would get hung up on a 2-minute curl timeout if you were running in a context without IMDS, such as in a container. Now if IMDS is not available within 1 second curl times out and 'unknown' is used instead
```
[ perf record: Woken up 1 times to write data ]
[ perf record: …
```
=> perfrunbook utility fixes

software/librdkafka.md
Upon using 2.0.2 throws below error
#error "confluent-kafka-python requires librdkafka v2.3.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
The minimum version required is 2.3.0 for both python 2 and 3. Tried and tested with both python2 and python3.7  for librdkafka 2.3.0
=> Update librdkafka.md with minimum version requirement to 2.3.0

c-c++.md
Fix typo for recommended compiler flags for Graviton2+ on C/C++ programs.
=> Fix typo in recommended compiler flage for c-c++.md

perfrunbook/debug_hw_perf.md
Text read `>16.xlarge` but it should have said `>=`.  Updated for all instance types, and tested on c5.9xl, c6i.16xl and c5a.12xl.
=> perfrunbook: Correct instance-size text for PMU events

HPC/README.md
Add Cradle CFD (2024.1) to list of ISVs with Graviton support
=> hpc: Add Cradle CFD (2024.1) to list of ISVs with Graviton support

perfrunbook/debug_hw_perf.md
This PR adds an example usage of `perf c2c` and setting the `GRUB_CMDLINE_LINUX` for using SPE.
Related issues: https://github.com/aws/aws-graviton-getting-started/issues/415
=> setting GRUB_CMDLINE_LINUX, example usage of perf c2c

README.md, runtime-feature-detection.md, sample-code/hwcaps-test.c, sample-code/hwcaps.c
Add a section on runtime feature detection.
I still want to add any additional libraries for hwcaps and clean up references, etc.
<details>
<summary>
The code sample output on A1:
</summary>
```
* HWCAP_FP
* HWCAP_ASIMD
* HWCAP_EVTSTRM
* HWCAP_AES
* HWCAP_PMULL
* HWCAP_SHA1
* HWCAP_SHA2
* HWCAP_CRC32
HWCAP_ATOMICS
HWCAP_FPHP
HWCAP_ASIMDHP
* HWCAP_CPUID
HWCAP_ASIMDRDM
HWCAP_JSCVT
HWCAP_FCMA
HWCAP_LRCPC
HWCAP_DCPOP
HWCAP_SHA3
HWCAP_SM3
HWCAP_SM4
HWCAP_ASIMDDP
HWCAP_SHA512
HWCAP_SVE
HWCAP_ASIMDFHM
HWCAP_DIT
HWCAP_USCAT
HWCAP_ILRCPC
HWCAP_FLAGM
HWCAP_SSBS
HWCAP_SB
HWCAP_PACA
HWCAP_PACG
HWCAP2_DCPODP
HWCAP2_SVE2
HWCAP2_SVEAES
HWCAP2_SVEPMULL
HWCAP2_SVEBITPERM
HWCAP2_SVESHA3
HWCAP2_SVESM4
HWCAP2_FLAGM2
HWCAP2_FRINT
HWCAP2_SVEI8MM
HWCAP2_SVEF32MM
HWCAP2_SVEF64MM
HWCAP2_SVEBF16
HWCAP2_I8MM …
```
=> add a section on runtime feature detection

perfrunbook/optimization_recommendation.md
At least on my system, the old paths are directories, and the control file is called 'enabled' within those.
=> Correct mTHP enablement paths

amis_cf_sm.md
Updated distros versions, plus some cleanup:
- removed ubuntu 18.04, it has now reached ext security maintenance ;
- removed ubuntu 23/21.04 to declutter, they aren't LTS anyway ;
- added ubuntu 24.04 (LTS version) ;
- re-ordered distro in reverse-chronological order ;
- updated Suse from SP4 to SP6 ;
- updated examples to use Graviton3 based instances instead of Graviton2 based ones;
=> Update linux distributions versions

perfrunbook/utilities/install_perfrunbook_dependencies.sh
Changes: 
added support for Ubuntu24.04, Suse 15 SP6 and RHEL to the installation script.
Testing:
clone repo.
```shell
sudo ./install_perfrunbook_dependencies.sh
sudo ./capture_flamegraphs.sh oncpu 10
```
download the created SVG and check to show relevant elements.
=> Expand support for additional OSes

Monitoring_Tools_on_Graviton.md
Added an example of how to get a given instance type processor maximum frequency without having to launch an instance.
=> Adding API call to get cpu freq to monitoring tools

README.md
Amazon Corretto now supports dynamic linking of zlib, adjusting documentation.
*Issue #, if available:* 457
Updated documentation to reflect that Amazon Corretto now dynamically links to zlib on Linux platforms for 17+. Left a bit of context that older versions, diff platforms, and alternate JDK vendors may bundle without being too explicit. 
=> Amazon Corretto now supports dynamic linking of zlib, adjust zlib docs
